# Basic
title: 库先生
subtitle: 自留地
description: 欢迎来到我的个人网站~
# 头像里面的标题
avatarTitle: darling_shadow
# 头像里面的描述
avatarDesc: Java/iOS/Android
url: "https://darling-shadow.github.io/"

# Comment
comment:
    provider: duoshuo
    duoshuo:
     short_name: robotkang

# Social
social:
    weibo: darling_shadow
    weixing: darling_shadow 
    github: darling_shadow
    # twitter: 
    mail: darling_shadow@126.com
    csdn: darling_shadow

# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: 9a058f2ba465ac7b8ea1f64b48df87cb 

# Google Analytics
# 使用博客模板请去掉或者更换 id
#ga:
# id: UA-84134159-3   
#  host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: 主页

# Navigation buttons in the front page.s
nav:
    - {title: 文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}   
    - {title: 留言, description: liuyan, url: '/liuyan'}
    - {title: 资源, description: ziyuan, url: '/ziyuan'}
    - {title: 我, description: about, url: '/about'}

          
    

# Pagination
gems: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"


valine:
  enable: true
  appId: yqbY7daqyFWOk0EaXHGXFnpi-gzGzoHsz
  appKey: n9pBiRYKYX10tVI0e7b646Gk


